name: CI - Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: Run PHP CodeSniffer
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpcs, cs2pr

      - name: Install WordPress Coding Standards
        run: |
          composer install
          phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

      - name: Run PHPCS with WordPress Coding Standards
        run: phpcs --standard=WordPress --ignore=vendor/,node_modules/ --extensions=php --report=checkstyle . | cs2pr
