name: CI - Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: Run PHP CodeSniffer
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr, phpcs

      - name: Run PHPCS with WordPress Coding Standards
        uses: 10up/wpcs-action@v1.4.0
        with:
          standard: 'WordPress'
          paths: '.'
          extra_args: '--ignore=vendor/,node_modules/ --extensions=php'
